# Copyright 2025 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "frontend.conf"

appName = "iced-subscription-frontend"
play.http.router = prod.Routes

# Custom error handler
play.http.errorHandler = "uk.gov.hmrc.icedsubscriptionfrontend.config.ErrorHandler"

play.filters.enabled += play.filters.csp.CSPFilter

# Play Modules
# ~~~~
# Additional play modules can be added here

# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
# If you deploy your application to several instances be sure to use the same key!
# Not set here so that MDTP frontends share the same secret key in the local environment
# (see common.conf in frontend-bootstrap).
# In server environments the secret comes from app-config-common
# play.http.secret.key="GJksTovvmUhJw7I12WAkKtr9v2zLXvl0f2ZwZyhbjcyPNAeI3rMwapa82rmHPpOH"
play.modules.enabled += "uk.gov.hmrc.icedsubscriptionfrontend.config.DIModule"

http-verbs.retries.ssl-engine-closed-already.enabled = true

play.i18n.langs = ["en", "cy"]
play.i18n.langCookieHttpOnly = true

play.http.flash.httpOnly = true

play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"

microservice {

  services {
    auth {
      protocol = http
      host = localhost
      port = 8500
    }
  }

}

metrics.enabled = true

google-analytics {
  token = N/A
  host = auto
}

login {
  url = "http://localhost:9949/auth-login-stub/gg-sign-in"
  return-base = "http://localhost:9837"
}

session {
  timeoutSeconds = 900
  countdownSeconds = 120
}

eori-common-component-frontend {
  base = "http://localhost:6750"
  start = "/customs-enrolment-services/gbss/subscribe"
}

tracking-consent-frontend {
  gtm.container = "c"
}

contact-frontend {
  host = "http://localhost:9250"
  serviceId = "iced-subscription-frontend"
}

accessibility-statement.service-path = "/safety-and-security-subscription"

bas-gateway {
  sign.out.url = "http://localhost:9553/bas-gateway/sign-out-without-state"
}

play-frontend-hmrc {
  useRebrand = true
  forceServiceNavigation = true
}